Feat/init
juanfcarrillo/spaceapps pull request #3
Opened 2024-06-24 02:12 UTC by DavidTrujillo123

2024-06-24 02:31 UTC, juanfcarrillo reviewed
There's some issue, you forgot to add the @storyblok/astro to the package.json file. Check if you are ignoring this file

2024-06-24 04:14 UTC, ferjozsot23 requested changes, later dismissed
Looks great! just some recommendation for good practices

2024-06-24 04:14 UTC, ferjozsot23 commented on src/pages/colegio.astro
> +import { useStoryblokApi } from '@storyblok/astro'
Try to not add plenty blank spaces

2024-06-24 04:14 UTC, ferjozsot23 commented on src/pages/colegio.astro
> +
Same here

2024-06-24 04:14 UTC, ferjozsot23 commented on src/components/ejemplo.astro
We can keep the file names in English for consistency

2024-06-25 03:04 UTC, juanfcarrillo approved these changes
🚀

2024-06-25 03:05 UTC, merged